export interface Translations {
    English:string;
    Arabic:string;
    Home: string;
    About: string;
    contact: string;
    Services: string;
    ServicesSubhead: string;
    ContactUs: string;
    bookVisit: string;
    location: string;
    daily: string;
    Service: string;
    Address: string;
    ServiceTimes: string;
    ANewChapterinSkinHairCare: string;
    OurStory: string;
    WhyUS: string;
    whyus_1: string;
    whyus_2: string;
    whyus_3: string;
    ServiceNotFound:string;
    SelectService:string;
    FindOurMore: string;
    welcome:string;
    WelcometoOurClinic: string;
    WelcometoOurClinic_text: string;
    SkinTreatments: string;
    HydraFacialDeepCleansing: string;
    HydraFacialDeepCleansingDesc: string;
    HairRestoration: string;
    PlasmaPRPTherapy: string;
    PlasmaPRPTherapyDesc: string;
    ScarPigmentationSolutions: string;
    ScarPigmentationSolutionsDesc: string;
    SkinBoostersMesotherapy: string;
    SkinBoostersMesotherapyDesc: string;
    ExosomeHairRegeneration: string;
    ExosomeHairRegenerationDesc: string;
    GCellTherapy: string;
    GCellTherapyDesc: string;
    SignatureHairPackage: string;
    SignatureHairPackageDesc: string;
    RFMicroneedling: string;
    RFMicroneedlingDesc: string;
    Laser:string;
    LaserHairRemoval: string;
    LaserHairRemovalDesc: string;
    LaserTattooRemoval: string;
    LaserTattooRemovalDesc: string;
    BridalPackages: string;
    BridalPackagesDesc: string;
    ViewDetails: string;
    ViewAllServices: string;
    ClinicName: string;
    WhereYourBeauty: string;
    HasItsOwnSignature: string;
    MainTitleHero: string;
    MainTitleHero2: string;
    subtitleHero: string;
    subtitleHero2: string;
    subtitleHero3: string;
    ContactUsSubhead: string;
    AboutUssubhead: string;
    FormSubTitle: string;
    FormMainTitle: string;
    Name: string;
    Phone: string;
    EMAIL: string;
    Treatment: string;
    MakeanAppointment: string;
    Time: string;
    Date: string;
    OurTeam: string;
    ViewAllDoctors: string;
    ContactInformation: string;
    contactInformationText: string;
    CustomerReview: string;
    MaithahSalem: string;
    MaithahSalemReview: string;
    Sara: string;
    SaraReview: string;
    NoranKhalilReview: string;
    NoranKhalil: string;
    ShayneGarcia: string;
    ShayneGarciaReview: string;
    GetYourFreeConsultation: string;
    BeforeAndAfter: string;
    BodyTreatments: string;
    Bodyfiller: string;
    BodyfillerDesc: string;
    IVDrips: string;
    IVDripsDesc: string;
    aboutTitle: string;
    aboutDescription: string;
    aboutKeys: string;
    serviceTitle: string;
    serviceDescription: string;
    serviceKeys: string;
    contactTitle: string;
    contactDescription: string;
    contactKeys: string;
    homeTitle:string;
    homeDescription:string;
    homeKeys:string;
    
  }
  